// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace MeterAPI.Models;

public partial class AppDbContext : DbContext
{
    IConfiguration Configuration = new ConfigurationBuilder()
    .SetBasePath(Directory.GetCurrentDirectory())
    .AddJsonFile("appsettings.json")
    .Build();
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Client> Clients { get; set; }

    public virtual DbSet<DailyReading> DailyReadings { get; set; }

    public virtual DbSet<Meter> Meters { get; set; }

    public virtual DbSet<MeterEvent> MeterEvents { get; set; }

    public virtual DbSet<Model> Models { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_general_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<Client>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("client");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(200)
                .HasColumnName("address");
            entity.Property(e => e.Document)
                .HasMaxLength(20)
                .HasColumnName("document");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .HasColumnName("email");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Phone)
                .HasMaxLength(20)
                .HasColumnName("phone");
            entity.Property(e => e.TypePerson)
                .HasMaxLength(1)
                .HasColumnName("type_person");
        });

        modelBuilder.Entity<DailyReading>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("daily_reading");

            entity.HasIndex(e => e.MeterId, "meter_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ActiveEnergyDirectIntermediate)
                .HasPrecision(10, 2)
                .HasColumnName("active_energy_direct_intermediate");
            entity.Property(e => e.ActiveEnergyDirectOffpeak)
                .HasPrecision(10, 2)
                .HasColumnName("active_energy_direct_offpeak");
            entity.Property(e => e.ActiveEnergyDirectPeak)
                .HasPrecision(10, 2)
                .HasColumnName("active_energy_direct_peak");
            entity.Property(e => e.ActiveEnergyReverseIntermediate)
                .HasPrecision(10, 2)
                .HasColumnName("active_energy_reverse_intermediate");
            entity.Property(e => e.ActiveEnergyReverseOffpeak)
                .HasPrecision(10, 2)
                .HasColumnName("active_energy_reverse_offpeak");
            entity.Property(e => e.ActiveEnergyReversePeak)
                .HasPrecision(10, 2)
                .HasColumnName("active_energy_reverse_peak");
            entity.Property(e => e.AvgCurrent)
                .HasPrecision(6, 2)
                .HasColumnName("avg_current");
            entity.Property(e => e.AvgVoltage)
                .HasPrecision(6, 2)
                .HasColumnName("avg_voltage");
            entity.Property(e => e.MaxDemand)
                .HasPrecision(10, 2)
                .HasColumnName("max_demand");
            entity.Property(e => e.MeterId).HasColumnName("meter_id");
            entity.Property(e => e.PowerFactor)
                .HasPrecision(5, 2)
                .HasColumnName("power_factor");
            entity.Property(e => e.ReactiveEnergyTotal)
                .HasPrecision(10, 2)
                .HasColumnName("reactive_energy_total");
            entity.Property(e => e.ReadingDate).HasColumnName("reading_date");

            entity.HasOne(d => d.Meter).WithMany(p => p.DailyReadings)
                .HasForeignKey(d => d.MeterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("daily_reading_ibfk_1");
        });

        modelBuilder.Entity<Meter>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("meter");

            entity.HasIndex(e => e.ClientId, "client_id");

            entity.HasIndex(e => e.ModelId, "fk_meter_model");

            entity.HasIndex(e => e.SerialNumber, "serial_number").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.ClientId).HasColumnName("client_id");
            entity.Property(e => e.InstallationLocation)
                .HasMaxLength(200)
                .HasColumnName("installation_location");
            entity.Property(e => e.IsActive)
                .HasDefaultValueSql("'1'")
                .HasColumnName("is_active");
            entity.Property(e => e.ModelId).HasColumnName("model_id");
            entity.Property(e => e.SerialNumber)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("serial_number");

            entity.HasOne(d => d.Client).WithMany(p => p.Meters)
                .HasForeignKey(d => d.ClientId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("meter_ibfk_1");

            entity.HasOne(d => d.Model).WithMany(p => p.Meters)
                .HasForeignKey(d => d.ModelId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("fk_meter_model");
        });

        modelBuilder.Entity<MeterEvent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("meter_event");

            entity.HasIndex(e => e.MeterId, "meter_id");

            entity.HasIndex(e => e.ReadingId, "reading_id");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.EventDatetime)
                .HasColumnType("timestamp")
                .HasColumnName("event_datetime");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("event_type");
            entity.Property(e => e.MeterId).HasColumnName("meter_id");
            entity.Property(e => e.ReadingId).HasColumnName("reading_id");

            entity.HasOne(d => d.Meter).WithMany(p => p.MeterEvents)
                .HasForeignKey(d => d.MeterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("meter_event_ibfk_1");

            entity.HasOne(d => d.Reading).WithMany(p => p.MeterEvents)
                .HasForeignKey(d => d.ReadingId)
                .HasConstraintName("meter_event_ibfk_2");
        });

        modelBuilder.Entity<Model>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("model");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Class)
                .IsRequired()
                .HasMaxLength(1)
                .HasColumnName("class");
            entity.Property(e => e.Code)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("code");
            entity.Property(e => e.Description)
                .HasMaxLength(200)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Nominal).HasColumnName("nominal");
            entity.Property(e => e.NominalFrequency).HasColumnName("nominal_frequency");
            entity.Property(e => e.NumberPhases).HasColumnName("number_phases");
            entity.Property(e => e.NumberWires).HasColumnName("number_wires");
            entity.Property(e => e.RatedVoltage).HasColumnName("rated_voltage");
        });

        OnModelCreatingPartial(modelBuilder);
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.UseMySql(Configuration.GetConnectionString("DefaultConnection"),
    ServerVersion.AutoDetect(Configuration.GetConnectionString("DefaultConnection")));

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}