// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MeterAPI.Models;

public partial class DailyReading
{
    public int Id { get; set; }

    public int MeterId { get; set; }

    public DateTime ReadingDate { get; set; }

    public decimal? ActiveEnergyDirectPeak { get; set; }

    public decimal? ActiveEnergyDirectOffpeak { get; set; }

    public decimal? ActiveEnergyDirectIntermediate { get; set; }

    public decimal? ActiveEnergyReversePeak { get; set; }

    public decimal? ActiveEnergyReverseOffpeak { get; set; }

    public decimal? ActiveEnergyReverseIntermediate { get; set; }

    public decimal? ReactiveEnergyTotal { get; set; }

    public decimal? MaxDemand { get; set; }

    public decimal? PowerFactor { get; set; }

    public decimal? AvgVoltage { get; set; }

    public decimal? AvgCurrent { get; set; }

    public virtual Meter Meter { get; set; }

    public virtual ICollection<MeterEvent> MeterEvents { get; set; } = new List<MeterEvent>();
}