// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MeterAPI.Models;

public partial class MeterEvent
{
    public int Id { get; set; }

    public int MeterId { get; set; }

    public int? ReadingId { get; set; }

    public DateTime EventDatetime { get; set; }

    public string EventType { get; set; }

    public string Description { get; set; }

    public virtual Meter Meter { get; set; }

    public virtual DailyReading Reading { get; set; }
}