// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MeterAPI.Models;

public partial class Meter
{
    public int Id { get; set; }

    public string SerialNumber { get; set; }

    public string Model { get; set; }

    public string PhaseType { get; set; }

    public int ClientId { get; set; }

    public string InstallationLocation { get; set; }

    public bool? IsActive { get; set; }

    public virtual Client Client { get; set; }

    public virtual ICollection<DailyReading> DailyReadings { get; set; } = new List<DailyReading>();

    public virtual ICollection<MeterEvent> MeterEvents { get; set; } = new List<MeterEvent>();
}