// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MeterAPI.Models;

public partial class Model
{
    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Class { get; set; }

    public int NumberPhases { get; set; }

    public int NumberWires { get; set; }

    public int Nominal { get; set; }

    public int NominalFrequency { get; set; }

    public int RatedVoltage { get; set; }

    public virtual ICollection<Meter> Meters { get; set; } = new List<Meter>();
}